server:
  port: 6002
  servlet:
    context-path: /springboot-nacos-discovery
spring:
  application:
    name: springboot-nacos-discovery
nacos:
  discovery:
    server-addr: localhost:8848
    namespace: 7e98b650-0c03-4663-b747-b3d4848630aa


